import { test, expect } from '@playwright/test';
import { existsSync } from 'fs';
import { join } from 'path';
import { freshSession, waitForTerminal } from './_helpers';

// The cached-examples flow depends on `public/example-fjms/manifest.json`
// being present. In CI the prebuild step (`tsx scripts/build-example-index.ts`)
// always creates this file. Locally it's also generated by `predev` /
// `prebuild`. If it's not there (e.g. during a non-standard run), skip
// rather than fail — the e2e suite must remain runnable.
const MANIFEST_PATH = join(process.cwd(), 'public/example-fjms/manifest.json');
test.skip(!existsSync(MANIFEST_PATH), 'manifest.json not present');

test.describe('Cached example .fjm path', () => {
  test('Hello World run hits /api/cached-compile and emits four (cached) lines', async ({ page }) => {
    // Clear any prior localStorage so we get the default state.
    await page.goto('/');
    await page.evaluate(() => {
      localStorage.clear();
      sessionStorage.clear();
      localStorage.setItem('fj-visited', '1');
    });

    const cachedHits: string[] = [];
    const compileHits: string[] = [];
    page.on('request', (req) => {
      const url = req.url();
      // Order matters — /api/cached-compile contains "/api/compile" as a
      // substring, so we must check the more-specific URL first.
      if (url.includes('/api/cached-compile')) cachedHits.push(url);
      else if (/\/api\/compile(?:[?#]|$)/.test(url)) compileHits.push(url);
    });

    await freshSession(page);

    // Pick Hello World from the Examples dropdown (it loads the canonical
    // content that should hash-match the manifest).
    await page.locator('button[title="Load a built-in example"]').click();
    await page.locator('button:has-text("Hello World")').click();

    // Run FJ.
    await page.locator('button[title="Compile and run FJ online"]').click();
    await waitForTerminal(page, /Hello, World!/);
    await waitForTerminal(page, /\(cached\)/);

    expect(cachedHits.length).toBeGreaterThan(0);
    expect(compileHits.length).toBe(0);
  });

  test('Editing a cached example invalidates the cache and falls back to /api/compile', async ({ page }) => {
    await page.goto('/');
    await page.evaluate(() => {
      localStorage.clear();
      sessionStorage.clear();
      localStorage.setItem('fj-visited', '1');
    });

    const cachedHits: string[] = [];
    const compileHits: string[] = [];
    page.on('request', (req) => {
      const url = req.url();
      // Order matters — /api/cached-compile contains "/api/compile" as a
      // substring, so we must check the more-specific URL first.
      if (url.includes('/api/cached-compile')) cachedHits.push(url);
      else if (/\/api\/compile(?:[?#]|$)/.test(url)) compileHits.push(url);
    });

    await freshSession(page);

    await page.locator('button[title="Load a built-in example"]').click();
    await page.locator('button:has-text("Hello World")').click();

    // Touch the editor to invalidate the cache hash.
    await page.locator('.monaco-editor').click();
    await page.keyboard.type(' // NOT-CACHED');

    // Reset request log so we only count THIS run's requests.
    cachedHits.length = 0;
    compileHits.length = 0;

    await page.locator('button[title="Compile and run FJ online"]').click();
    await waitForTerminal(page, /Process exited \(code 0\)/);

    expect(compileHits.length).toBeGreaterThan(0);
    expect(cachedHits.length).toBe(0);
  });
});
