#!/usr/bin/env node
// Mock c2fj used by tests. Real c2fj requires make + RISC-V toolchain
// which we don't want CI to install. This stand-in implements just enough
// of the surface that route.ts depends on:
//   c2fj --build-dir <dir> --unify-fj --finish-after fj <source>
// and writes a known unified.fj into the build dir so the route's
// success path can be exercised.

import { writeFile, mkdir, readFile } from 'fs/promises';
import { existsSync } from 'fs';
import { join } from 'path';
import process from 'process';

async function main() {
  const args = process.argv.slice(2);

  const buildIdx = args.indexOf('--build-dir');
  if (buildIdx === -1 || buildIdx + 1 >= args.length) {
    console.error('mock-c2fj: --build-dir required');
    process.exit(2);
  }
  const buildDir = args[buildIdx + 1];

  const sourcePath = args[args.length - 1];
  if (!existsSync(sourcePath)) {
    console.error(`mock-c2fj: source not found: ${sourcePath}`);
    process.exit(2);
  }
  // Read source to ensure the route actually wrote it where we expect.
  const sourceLen = (await readFile(sourcePath)).byteLength;

  await mkdir(buildDir, { recursive: true });
  const out = [
    `// generated by mock-c2fj from ${sourcePath} (${sourceLen} bytes)`,
    'stl.startup',
    "stl.output_char 'C'",
    "stl.output_char '\\n'",
    'stl.loop',
    '',
  ].join('\n');
  await writeFile(join(buildDir, 'unified.fj'), out, 'utf8');
}

main().catch((err) => {
  console.error(`mock-c2fj: ${err.message}`);
  process.exit(1);
});
